description: >
  Select the version of Nim tooling to use.
docker:
  - image: 'nimlang/nim:<<parameters.version>>'
parameters:
  version:
    default: latest
    description: Select a Nim version, i.e. "0.16.0"
    type: string
